name: evegah_rider_app

description: "eVegah Rider App - Find and ride electric bikes near you."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.5

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # NETWORK
  http: ^1.6.0

  # STORAGE
  shared_preferences: ^2.2.3

  # FILES & IMAGES
  file_picker: ^8.0.0+1
  image_picker: ^1.1.2

  # QR SCANNER
  mobile_scanner: ^5.1.1

  # BLUETOOTH
  flutter_blue_plus: ^1.32.8
  permission_handler: ^11.3.1

  # URL LAUNCHER
  url_launcher: ^6.3.0

  # LOCATION
  geolocator: ^11.0.0

  # PDF
  pdf: ^3.10.8
  printing: ^5.11.1

  # GOOGLE MAPS
  google_maps_flutter: ^2.6.0
  google_maps_flutter_web: ^0.5.7

  # CLUSTER MANAGER
  google_maps_cluster_manager:
    git:
      url: https://github.com/bpillon/google_maps_cluster_manager.git
      ref: master

  # RAZORPAY
  razorpay_flutter: ^1.4.5

  # DEVICE INFO
  device_info_plus: ^12.4.0
  flutter_svg: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/